# Generated by Django 5.0.6 on 2024-05-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tags_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
