# Generated by Django 4.2.13 on 2024-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tags_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='polls.tags'),
        ),
    ]
